<?php

namespace Kinash\BatteryRecycleBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * BatteryPackRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BatteryPackRepository extends EntityRepository
{

    /**
     * Calculate count of Each type of Batteries
     * @return array
     */
    public function calculateBatteries()
    {
       $builder = $this->createQueryBuilder('b')
            ->addSelect('SUM(b.count) as cnt')
            ->addSelect('b.type')
            ->groupBy('b.type')
            ->orderBy('cnt', 'DESC');
       return $builder->getQuery()->getResult();
    }


    /**
     * Remove all rows from batterPack table
     * @return array
     */
    public function truncate()
    {
        return $this->createQueryBuilder('b')->delete()->getQuery()->getResult();
    }
}
